
from building import *
import rtconfig

cwd = GetCurrentDir()

src = []

src += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('robots', src, depend = ['PKG_USING_ROBOTS'], CPPPATH = CPPPATH)

Return('group')
